name: file_type_dart
description: A Dart library for detecting file types from bytes, streams, or URLs by examining the files binary signature.
version: 1.0.0
repository: https://github.com/DitzDev/file-type
homepage: https://github.com/DitzDev/file-type
issue_tracker: https://github.com/
DitzDev/file-type/issues


environment:
  sdk: ^3.7.3

dependencies:
  http: ^1.4.0
  meta: ^1.17.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  path: ^1.9.1
  mockito: ^5.4.6
  build_runner: ^2.4.15
